name: CD (Continuous Delivery)

on:
  push:
    branches:["main"]

jobs:

  build-push:
    name: Build and Push Image to DockerHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{secret.DOCKERHUB_USERNAME}}
            password: ${{secret.DOCKERHUB_TOKEN}}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{secret.DOCKERHUB_USERNAME}}/flaskapp:${{github.run_number}}

